<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = array();
$labels['plugin_xbackground'] = 'Hintergrund';
$labels['plugin_xcalendar'] = 'Kalender';
$labels['plugin_xdropbox'] = 'DropBox';
$labels['plugin_xgoogle_drive'] = 'Google Drive';
$labels['plugin_xlast_login'] = 'Letzte Anmeldung';
$labels['plugin_xquote'] = 'Zitat des Tages';
$labels['plugin_xnews_feed'] = 'News-Feed';
$labels['plugin_xsignature'] = 'Signatur';
$labels['plugin_xskin'] = 'Skins';
$labels['plugin_xvertical_preview'] = 'Vertikale Vorschau';
$labels['plugin_xweather'] = 'Wetter';
$labels['plugin_xtag'] = 'Tag-Manager';
$labels['plugin_xemail_schedule'] = 'E-Mails planen';
$labels['plugin_x2fa'] = 'Zwei-Faktor-Authentifizierung';
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google Drive';
$labels['xwebdav_name'] = 'Cloud';
$labels['insert_link'] = 'Link zur Nachricht einfügen';
$labels['download_and_attach'] = 'Herunterladen und hinzufügen';
$labels['sidebar'] = 'Sidebar';
$labels['sidebar_items'] = 'Sidebar-Elemente';
$labels['sidebar_change_order'] = 'Verschieben Sie die Sidebar-Elemente per Drag&Drop, um ihre Reihenfolge zu ändern.';
$labels['buy_now'] = 'Jetzt kaufen';
$labels['preview'] = 'Vorschau';
$labels['apps'] = 'Apps';
$labels['sidebar'] = 'Sidebar';
$labels['hide'] = 'Ausblenden';
$labels['invalid_image_extension'] = "Ungültige Dateiendung. Erlaubte Endungen: .jpg, .jpeg, .png, .gif.";
$labels['invalid_image_format'] = "Die Datei ist kein gültiges Bild";