<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = array();
$labels['plugin_xbackground'] = 'Arrière-plan';
$labels['plugin_xcalendar'] = 'Agenda';
$labels['plugin_xdropbox'] = 'DropBox';
$labels['plugin_xgoogle_drive'] = 'Google Drive';
$labels['plugin_xlast_login'] = 'Dernière connexion';
$labels['plugin_xquote'] = 'Citation quotidienne';
$labels['plugin_xnews_feed'] = 'Fil d\'actualité';
$labels['plugin_xsignature'] = 'Signature';
$labels['plugin_xskin'] = 'Thèmes';
$labels['plugin_xvertical_preview'] = 'Aperçu vertical';
$labels['plugin_xweather'] = 'Météo';
$labels['plugin_xtag'] = 'Gestionnaire de balises';
$labels['plugin_xemail_schedule'] = 'Planification des emails';
$labels['plugin_x2fa'] = 'Authentification à deux facteurs';
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google Drive';
$labels['xwebdav_name'] = 'Cloud';
$labels['insert_link'] = 'Insérer un lien vers le message';
$labels['download_and_attach'] = 'Télécharger et joindre';
$labels['sidebar'] = 'Barre latérale';
$labels['sidebar_items'] = 'Éléments de la barre latérale';
$labels['sidebar_change_order'] = 'Faites glisser et déposez les éléments de la barre latérale pour modifier leur ordre.';
$labels['buy_now'] = 'Acheter maintenant';
$labels['preview'] = 'Aperçu';
$labels['apps'] = 'Apps';
$labels['sidebar'] = 'Sidebar';
$labels['hide'] = 'Cacher';
$labels['invalid_image_extension'] = "Extension d'image non valide. Les extensions autorisées sont : jpg, jpeg, png, gif.";
$labels['invalid_image_format'] = "Ce fichier n'est pas une image valide.";