<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = array();
$labels['plugin_xbackground'] = 'Tło';
$labels['plugin_xcalendar'] = 'Kalendarz';
$labels['plugin_xdropbox'] = 'DropBox';
$labels['plugin_xgoogle_drive'] = 'Google Drive';
$labels['plugin_xlast_login'] = 'Ostatnie logowanie';
$labels['plugin_xquote'] = 'Cytat Dnia';
$labels['plugin_xnews_feed'] = 'Wiadomości';
$labels['plugin_xsignature'] = 'Podpis';
$labels['plugin_xskin'] = 'Skórki';
$labels['plugin_xvertical_preview'] = 'Pionowy podgląd';
$labels['plugin_xweather'] = 'Pogoda';
$labels['plugin_xtag'] = 'Menedżer znaczników';
$labels['plugin_xemail_schedule'] = 'Planowanie wiadomości';
$labels['plugin_x2fa'] = 'Uwierzytelnianie dwuskładnikowe';
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google Drive';
$labels['xwebdav_name'] = 'Cloud';
$labels['insert_link'] = 'Wpisz link do wiadomości';
$labels['download_and_attach'] = 'Pobierz i załącz';
$labels['sidebar'] = 'Pasek boczny';
$labels['sidebar_items'] = 'Obiekty na pasku bocznym';
$labels['sidebar_change_order'] = 'Przeciągnij i upuść obiekty na pasku bocznym, aby zmienić ich kolejność.';
$labels['buy_now'] = 'Kup teraz';
$labels['preview'] = 'Podgląd';
$labels['apps'] = 'Aplikacje';
$labels['sidebar'] = 'Pasek boczny';
$labels['hide'] = 'Ukryj';
$labels['invalid_image_extension'] = "Niewłaściwe rozszerzenie pliku obrazu. Dostępne rozszerzenia to: jpg, jpeg, png, gif.";
$labels['invalid_image_format'] = "Ten plik nie jest obrazem.";
