<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = array();
$labels['plugin_xbackground'] = 'Фон';
$labels['plugin_xcalendar'] = 'Календарь';
$labels['plugin_xdropbox'] = 'DropBox';
$labels['plugin_xgoogle_drive'] = 'Google Drive';
$labels['plugin_xlast_login'] = 'Последний вход';
$labels['plugin_xquote'] = 'Ежедневная цитата';
$labels['plugin_xnews_feed'] = 'Новостная лента';
$labels['plugin_xsignature'] = 'Подпись';
$labels['plugin_xskin'] = 'Скины';
$labels['plugin_xvertical_preview'] = 'Вертикальный просмотр';
$labels['plugin_xweather'] = 'Погода';
$labels['plugin_xtag'] = 'Тэг менеджер';
$labels['plugin_xemail_schedule'] = 'Расписание электронной почты';
$labels['plugin_x2fa'] = 'Двухфакторная аутентификация';
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google Drive';
$labels['xwebdav_name'] = 'Cloud';
$labels['insert_link'] = 'Вставить ссылку в сообщение';
$labels['download_and_attach'] = 'загрузить и прикрепить';
$labels['sidebar'] = 'Боковая панель';
$labels['sidebar_items'] = 'Элементы боковой панели';
$labels['sidebar_change_order'] = 'Перетащите элементы боковой панели, чтобы изменить их порядок.';
$labels['buy_now'] = 'Купить сейчас';
$labels['preview'] = 'Предварительный просмотр';
$labels['apps'] = 'Приложения';
$labels['sidebar'] = 'Боковая панель';
$labels['hide'] = 'Спрятать';
$labels['invalid_image_extension'] = "Неверное расширение изображения. Допустимые расширения: jpg, jpeg, png, gif.";
$labels['invalid_image_format'] = "Этот файл не является действительным изображением.";

