<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = array();
$labels['plugin_xbackground'] = 'Фон';
$labels['plugin_xcalendar'] = 'Календар';
$labels['plugin_xdropbox'] = 'DropBox';
$labels['plugin_xgoogle_drive'] = 'Google Drive';
$labels['plugin_xlast_login'] = 'Останній вхід';
$labels['plugin_xquote'] = 'Щодня цитата';
$labels['plugin_xnews_feed'] = 'Стрічка новин';
$labels['plugin_xsignature'] = 'Підпис';
$labels['plugin_xskin'] = 'Скіни';
$labels['plugin_xvertical_preview'] = 'Вертикальний перегляд';
$labels['plugin_xweather'] = 'Погода';
$labels['plugin_xtag'] = 'Тег менеджер';
$labels['plugin_xemail_schedule'] = 'Розклад електронної пошти';
$labels['plugin_x2fa'] = 'Двофакторна автентифікація';
$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google Drive';
$labels['xwebdav_name'] = 'Cloud';
$labels['insert_link'] = 'ставити посилання в повідомлення';
$labels['download_and_attach'] = 'Завантаити та додати';
$labels['sidebar'] = 'Бічна панель';
$labels['sidebar_items'] = 'Елементи бічної панелі';
$labels['sidebar_change_order'] = 'Перетягніть елементи бічної панелі, щоб змінити їх розташування.';
$labels['buy_now'] = 'Придбати зараз';
$labels['preview'] = 'Попередній перегляд';
$labels['apps'] = 'Програми';
$labels['sidebar'] = 'Бічна панель';
$labels['hide'] = 'Приховати';
$labels['invalid_image_extension'] = "Недійсне розширення зображення. Дозволеними розширеннями є: jpg, jpeg, png, gif.";
$labels['invalid_image_format'] = "Цей файл не є дійсним зображенням.";
